= Test Drive New Features of {productname-long}
:!sectids:

[.text-center.strong]
== Introduction

Welcome!

In this {deliverable}, you'll start with the basics of {productname-short}, and end with some of the newest and most advanced features.

We'll start with a straightforward fraud detection model built with Tensorflow to learn the basics.  Then we'll progress to some new features of {productname-short} that allow it to be a great platform for generative AI and large language models.  This will include distributed training and LLM model serving with CaiKit

You'll use an example fraud detection model to complete the following tasks:

* Explore a pre-trained fraud detection model by using Jupyter Notebooks.
* Deploy the model by using {productname-short} model serving.
* Integrate the model into a real-time fraud detection application.
* Refine and train the model by using automated pipelines.

And you'll do all of this without having to install anything on your own computer, thanks to https://www.redhat.com/en/technologies/cloud-computing/openshift/openshift-data-science[{productname-long}].

== About the example fraud detection model

The example fraud detection model mentors credit card transactions for potential fraudulent activity. It analyzes the following credit card transaction details:

* The geographical distance from the previous credit card transaction.
* The price of the current transaction, compared to the median price of all the user’s transactions.
* Whether the user completed the transaction by using the hardware chip in the credit card,  entered a PIN number, or for an online purchase.

Based on this data, the model outputs the likelihood of the transaction being fraudulent.

== Before you begin

https://developers.redhat.com/products/red-hat-openshift-data-science/download[Set up your {productname-long} environment]

If you don't already have an instance of {productname-long}, find out more on the https://developers.redhat.com/products/red-hat-openshift-data-science/download[developer page]. There, you can spin up your own account on the *free {productname-short} Sandbox* or learn about installing on *your own OpenShift cluster*.

If you're ready, xref:setup:navigating-to-the-dashboard.adoc[start the {deliverable}!]
