= Test Drive New Features of {productname-long}
include::_attributes.adoc[]
:!sectids:

[.text-center.strong]
== Introduction

Welcome!

In this {deliverable}, you will start with the basics of {productname-short}, and end with some of the newest features.

If you've never used {productname-short}, don't worry.  We will start with a straightforward fraud detection model built with Tensorflow to learn the basics.  Then we will progress to some new features of {productname-short} that allow it to be a great platform for generative AI and large language models (LLMs).  This will include distributed training and LLM model serving.

You will use an example fraud detection model to complete the following tasks:

* Explore a fraud detection model by using Jupyter Notebooks.
* Deploy the model by using {productname-short} single model serving.
* Refine and train the model by using automated pipelines.

Using an LLM (Google's https://huggingface.co/google/flan-t5-small[flan-t5-small,window=_blank]), we will complete the following tasks:

* Download the model from HuggingFace
* Upload it into our Object Storage
* Serve it with RHOAI's Single Model serving
