= Generative AI {deliverable} with {productname-long}
:!sectids:

== Introduction

Now that you've learned the basics of {productname-long} using a Predictive AI model, it's time to explore Generative AI. Generative AI is a subset of artificial intelligence that uses machine learning to generate new data. It's used in a variety of applications, including image generation, text generation, and music generation.

In this {deliverable}, we'll explore using a large language model (LLM) downloaded from Huggingface.  We'll be using This is a small LLM we can use with minimal resources.

We'll apply a similar workflow from Predictive AI models to complete the following tasks:

* Convert a model from Huggingface to a format that Caikit serving can use.
* Deploy the model by using single-model serving with the Caikit runtime
* Test the model API

== About LLMs

Today, we'll be using Google's https://huggingface.co/google/flan-t5-small[flan-t5-small] because of compatibility, small size, and small requirements (no gpu).


If you're ready, xref:llm:caikit-conversion.adoc[let's get started!]
